cherry pick commit from `Skip restablish vtep (#63)`
dcos/navstar pull request #103
Opened 2018-10-02 02:57 UTC by mainred

* fix Restarting dcos-net causing traffic break

Reconfiging mac address of an interface will reset its static ip neighbours.
Thus, static ip neighbours of vtep interface will be removed,
if dcos_overlay is restarted, which results in traffic break.

Fix this by ignoring reconfiging an existing vtep interface.

Close-Bug: :DCOS_OSS-3855

* Do not remove vtep interface

do not remove vtep inteface for it can be created by user

* Reestablish vtep when its configuration up-to-date

vtep-${vni} does not conflicts with custom defined interface
for it's uniqueness, so it's safe to reestablish the interface
if its current configuration does not match that from mesos.

And add macro function `LINK_INFO` to replace complicated structure
from netlink used directly in function.

* add ut test and fix common test

* user rtnetlink record and refactor mactch function

- rtnetlink we get from iplink_show is record defined
[here](https://github.com/mesosphere/gen_netlink/blob/3b7fd37/include/netlink.hrl#L94-L100)

- `create_vtep` is extracted for reuse.

- `config_l3` uses vxlan record as parameter to be more extensible

* Unregister dcos_overlay_poller

* skip test dcos_overlay for non-root user

* use `_link` to label link-related functions

2018-10-02 05:06 UTC, mainred commented
@urbanserj @GoelDeepak  PTAL

2018-10-02 18:22 UTC, GoelDeepak approved these changes

2018-10-02 18:36 UTC, urbanserj requested changes

2018-10-02 18:36 UTC, urbanserj commented on apps/dcos_overlay/testdata/vtep_link.data
> +[
Please remove this file.

2018-10-02 23:07 UTC, mainred commented on apps/dcos_overlay/testdata/vtep_link.data
> +[
done

2018-10-02 23:10 UTC, urbanserj approved these changes

2018-10-02 23:11 UTC, merged

2018-10-03 00:15 UTC, urbanserj commented
@mainred it seems like your PR broke master branch in this repo. could you please take a look?

https://circleci.com/gh/dcos/navstar/510
https://circleci.com/gh/dcos/navstar/511
https://circleci.com/gh/dcos/navstar/512

2018-10-03 00:57 UTC, mainred commented
I am on it