Patch to refactor navstar overlay code
dcos/navstar pull request #26
Opened 2016-10-08 05:06 UTC by GoelDeepak

2016-10-08 19:13 UTC, GoelDeepak commented
@sargun This patch is ready for review

2016-10-09 00:24 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_helper.erl
> +run_command("ip link show dev vtep1024") ->
What do you think about converting these to netlink calls in a follow-up patch? I think it'd be valuable to talk about netlink, and the kernel interface next week?

2016-10-09 06:00 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_helper.erl
> +run_command("ip link show dev vtep1024") ->
Sounds good. Should I hold on this patch?

2016-10-10 22:48 UTC, GoelDeepak commented
@sargun  Should I merge this PR?

2016-10-12 16:38 UTC, sargun commented
@GoelDeepak go ahead. Are you going to follow up with the batching / short-circuiting updates?

2016-10-14 17:54 UTC, sargun requested changes

2016-10-14 17:54 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_helper.erl
> +%%%-------------------------------------------------------------------
I'm not sure about how I feel splitting this into its own file. I don't think it makes sense go cross-file since this code isn't reused anywhere.

2016-10-14 17:54 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_sup.erl
>      {ok, {{one_for_all, 5, 10}, [
Can this be rest for one?

2016-10-14 17:54 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +%%%-------------------------------------------------------------------
The way that this is written now, it's basically stateless. In this, it seems like this should be an ephemeral worker that either is a temporary process attached to the supervisor, or hangs off the gen_statem. Making it a full-blown thing seems a bit awkward.

2016-10-14 17:54 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    {ok, Ref} = lashup_kv_events_helper:start_link(ets:fun2ms(fun({[navstar, overlay, '_']}) -> true end)),
Let's upgrade to Erlang 19.1, and use Erlang 19.1's mechanism of specifying the callback mode.

2016-10-14 17:54 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    {keep_state, State1, ?LISTEN_TIMEOUT};
So, rather than using this, it makes a lot more sense to do something like have two states, applying, and listening. In the listening state, you listen for events, and use the event time out to apply that particular state. The action `{timeout, ?LISTEN_TIMEOUT, EventContent}` should allow this.

Once you receive this event, you should transition into the applying state, and postpone all events OR preempt the application process.

2016-10-14 21:47 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_helper.erl
> +%%%-------------------------------------------------------------------
Used by navstar_overlay_poller and navstar_overlay_configure.

2016-10-14 21:47 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    {ok, Ref} = lashup_kv_events_helper:start_link(ets:fun2ms(fun({[navstar, overlay, '_']}) -> true end)),
Done.

2016-10-14 21:47 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +%%%-------------------------------------------------------------------
Agree.

2016-10-14 21:47 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_sup.erl
>      {ok, {{one_for_all, 5, 10}, [
done.

2016-10-14 21:47 UTC, GoelDeepak commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    {keep_state, State1, ?LISTEN_TIMEOUT};
Added the state diagram

2016-10-17 18:15 UTC, GoelDeepak commented
@Sargun, I have incorporated your comments. Could you please take a look?

2016-10-19 06:51 UTC, GoelDeepak commented
@sargun This PR is ready for review

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +   spawn(?MODULE, handle_event, [Event]).
spawn_link?

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +handle_event(Event) ->
do_configure -- handle_event is already a concept from gen_fsm / gen_statem.

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +    lager:error("handle_event start"),
Why is this an error?

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +handle_event(Event) ->
maybe_configure?

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +    {_, AgentIP} = lists:keyfind({agent_ip, riak_dt_lwwreg}, 1, Value),
why not do case lists:keyfind({agent_ip, riak_dt_lwwreg}, 1, Value) of...?

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    {keep_state_and_data, {timeout, ?LISTEN_TIMEOUT, EventContent}};
It might be nice to pass something like {do_configure, EventContent} to differentiate it.

2016-10-20 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    Pid = navstar_overlay_configure:start(Event),
Don't we want to wait for the configuration to complete the first time? So the system will get into a semi-consistent state?

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +reply(Pid, Msg) ->
you might want to use gen_statem:cast

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +start(reply, LashupEvent) ->
These should probably be named start_link for consistency. Also, why not always reply?

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +            _Data = #data{ref = Ref}) when Ref == Reference, is_tuple(Subnet), tuple_size(Subnet) == 2 ->
you don't actually need to do when Ref == Reference, you can do #data{ref = Reference}, and it'll match.

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    lager:error("configuring-internal"),
We should add logging messages that actually have a little more data here.

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +    NewData = Data#data{pid = Pid},
Generally, you make a updated State data named something like Data0, and the new version Data1.

2016-10-20 07:32 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +configuring(info, _EventContent, Data) ->
Comment about the fact that this is interrupting configuration intentionally.

2016-10-24 23:24 UTC, sargun commented
LGTM. Let's test on 1K agents, and go for it.

2016-10-24 23:24 UTC, sargun approved these changes

2016-10-27 16:17 UTC, merged