Adds common test for navstar overlay
dcos/navstar pull request #30
Opened 2016-11-04 23:01 UTC by GoelDeepak

2016-11-05 00:01 UTC, GoelDeepak commented
@sargun

2016-11-10 19:53 UTC, sargun commented on apps/navstar_overlay/test/navstar_overlay_SUITE.erl
> +%% Borrowed from the ct_slave module
Why do we have to do this?

2016-11-10 20:00 UTC, GoelDeepak commented on apps/navstar_overlay/test/navstar_overlay_SUITE.erl
> +%% Borrowed from the ct_slave module
Copy & paste. I thought this is a safe was of shutting down a node. No?

2016-11-18 11:08 UTC, sargun requested changes

2016-11-18 11:08 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_configure.erl
> +    maybe_print_parameters([FormattedAgentIP, binary_to_list(VTEPName),
Maybe add a comment here indicating that this is a testing fixture

2016-11-18 11:08 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_helper.erl
> +-ifdef(TEST).
we want to make sure that these don't during both testing and dev.

2016-11-18 21:16 UTC, GoelDeepak commented
@sargun I have incorporated your comments. Do you have some more or this is fine to merge?

2016-11-21 23:52 UTC, sargun approved these changes

2016-11-22 07:22 UTC, merged