[WIP] Adds netlink to navstar overlay
dcos/navstar pull request #34
Opened 2016-11-30 06:20 UTC by GoelDeepak

2016-12-07 08:15 UTC, GoelDeepak commented
@sargun ... This is ready for review

2016-12-07 20:09 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_netlink.erl
> +-define(TEST_AND_DEV, true).
TEST_OR_DEV?

2016-12-07 20:12 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_netlink.erl
> +    _Ifindex = if_nametoindex(Ifname),
Please put this on a separate line.

2016-12-07 20:12 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_netlink.erl
> +    _Ifindex = if_nametoindex(Ifname),
In general, if you're doing something that has side-effects while initializing a Tuple, it's a bit difficult to track down when it breaks.

2016-12-07 20:14 UTC, sargun commented
Two things:
1) It would be good to add some tests
2) It would be good to have an "AAE" mode that runs every once in a while which makes sure all the neighbor and routes are matching as we expect them to be (non-delta config application)

2016-12-07 20:14 UTC, sargun commented
otherwise, looks good.

2016-12-13 00:19 UTC, sargun requested changes

2016-12-13 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +-type orddict() :: [{Key::term(), Value::term()}].
Any reason you're not using orddict:ordict(Type1, Type1)?

2016-12-13 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +-type config() :: orddict().
You should probably use orddict:orddict and specify the key and val types

2016-12-13 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +-spec(handle_event(LashupEvent :: tuple(), #data{}) -> #data{}).
Don't use handle_event, it's a special function name when gen_statem is in a different callback mode.

2016-12-13 00:19 UTC, sargun commented on apps/navstar_overlay/src/navstar_overlay_lashup_kv_listener.erl
> +handle_event({lashup_kv_events, #{type := ingest_new, key := OverlayKey, value := NewValue, ref := Ref}},
Can we come up with a better name than "Value" Maybe OverlayConfiguration?

2016-12-13 00:19 UTC, sargun commented on rebar.config
> +{relx, [{release, {'navstar', "0.1.0"}, [navstar, mnesia, eper, runtime_tools, eflame, debugger, observer, {gen_netlink, load}]},
Why `{gen_netlink, load}` It's okay to start it.

2016-12-16 21:30 UTC, merged